const YOUR_PLACE_BASE_URL = "http://localhost:5000";
const YOUR_PLACE_BASE_USERS_URL = "/api/users";
const YOUR_PLACE_BASE_PLACES_URL = "/api/places";

export const YOUR_PLACE_API_URLS = {
  LOGIN: `${YOUR_PLACE_BASE_URL}${YOUR_PLACE_BASE_USERS_URL}/login`,
  SIGNUP: `${YOUR_PLACE_BASE_URL}${YOUR_PLACE_BASE_USERS_URL}/signup`,
  USERS: `${YOUR_PLACE_BASE_URL}${YOUR_PLACE_BASE_USERS_URL}`,
};
